#%%
from sympy import SingularityFunction
from sympy import symbols
from sympy.physics.continuum_mechanics.beam import Beam

#%% 0. Get help on the Beam class
help(Beam)

#%% 1. Define symbolic variables
E, I, L = symbols('E I L', positive=True)
x = symbols('x', nonnegative=True) # Allows x to equal 0

#%% 2. Set up the symbolic beam
b = Beam(L, E, I, variable=x)
print(b.elastic_modulus)
print(b.second_moment)
print(b.variable)
help(b.apply_support)
# Capture the reaction variables generated by apply_support
R1=b.apply_support(0, type='pin')
R2=b.apply_support(L, type='roller')
print(b._applied_supports)
print(b._support_as_loads)
print(b.load)

# Apply a downward point load of 1000 N at mid-span
b.apply_load(-1000, L / 2, -1)
print(b.load)

# Solve the system symbolically
print(R1)
# help(b.solve_for_reaction_loads)
b.solve_for_reaction_loads(R1,R2)
print(b.reaction_loads)

print(b.load)

#%%
help(SingularityFunction)
#%% 3. Context Value: JSON-Safe Parameter Serialization
# import json
#
# # Keep keys as strings to make it compatible with json.dumps()
# params_dict = {
#     "L": 10.0,
#     "E": 2e11,  # Young's modulus (Pa)
#     "I": 1e-4   # Moment of inertia (m^4)
# }
#
# # Safely save to JSON (e.g., storing the state from a UI or database)
# json_data = json.dumps(params_dict)
# print("Serialized Parameters:", json_data)

# %% Reload and safely convert string keys back to SymPy symbols
import json5
from sympy import sympify, pprint

import os
os.getcwd()
params_json=os.path.join("data","params_si.json")
os.path.exists(params_json)
# 1. Reload the JSON
help(json5.load)
with open(params_json, 'r', encoding="utf-8") as f:
    reloaded_params = json5.load(f)
pprint(reloaded_params)


#%%
# 3. Silence Pyrefly by explicitly casting to a SymPy object
# (It doesn't change the math, just makes the linter happy)
# 2. Map values to your ACTUAL symbols (Option B used here for scalability)
b_deflection = b.deflection()

# pyrefly: ignore [missing-attribute]
original_symbols = {s.name: s for s in b_deflection.free_symbols}
sym_params = {original_symbols[k]: v for k, v in reloaded_params.items() if k in original_symbols}
pprint(sym_params)

# 3. Silence Pyrefly by explicitly casting to a SymPy object
# (It doesn't change the math, just makes the linter happy)

# 4. Substitute the numerical parameters
# pyrefly: ignore [missing-attribute]
numerical_deflection = b_deflection.subs(sym_params)
print("Deflection equation with constants:\n", numerical_deflection)

#%% 5. Calculate deflection precisely at mid-span (x = 5)
L_val=L.subs(sym_params)

mid_span_deflection = numerical_deflection.subs(x, L_val/2)

# Convert to float for a final clean number (evalf)
print(f"\nDeflection at mid-span: {mid_span_deflection.evalf()} meters")

# %%